### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [dluvian/voyage#129]
I've checked your app if its build is reproducible (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/catmin/articles/named/iod-rbs-mirrors-clients?lang=en)), but while I was able to successfully generate the APK using `./gradlew assembleRelease`, there are differences to the one provided at your latest release. Was that APK really built from the commit the tag points to? If so, did I miss some build options? And if not, which commit was it?

APK diff:

```diff
-------------------------------
--- /dev/fd/63  2024-07-12 13:03:25.689716036 +0200
+++ /dev/fd/62  2024-07-12 13:03:25.689716036 +0200
@@ -3,11 +3,11 @@
   META-INF/version-control-info.textproto
   32-bit CRC value (hex):                         1085a6dd
   assets/dexopt/baseline.prof
-  32-bit CRC value (hex):                         92ac2c59
+  32-bit CRC value (hex):                         c51ccb62
   assets/dexopt/baseline.profm
   32-bit CRC value (hex):                         fc8dffb0
   classes.dex
-  32-bit CRC value (hex):                         9431342c
+  32-bit CRC value (hex):                         69d76943
   lib/arm64-v8a/libjnidispatch.so
   32-bit CRC value (hex):                         11d795f0
   lib/arm64-v8a/libnostr_ffi.so
```

The dex diff was quite huge, so I rather not include this here.

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Looking forward to your reply!

**Comment by dluvian** [comment]
> (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/catmin/articles/named/iod-rbs-mirrors-clients?lang=en))

Opening this site requires me to log in, but I don't have the credentials.

> Was that APK really built from the commit the tag points to?

I'd say probably not. I think I build first and then committed 82b4c2b2387db34ec9d543324e8225b9782edc9d (which was in the work tree when building the apk) followed by the 2 other commits that only changed the README file.

> We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that.

Thank you. I will keep this document in mind when publishing the next release

**Comment by IzzySoft** [comment]
> Opening this site requires me to log in, but I don't have the credentials.

Yuck, typo, sorry. Try this one: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)

> I think I build first and then committed

Ah, the cardinal sin of §1 violation then :see_no_evil:

> I will keep this document in mind when publishing the next release

Wonderful! Can you give me a ping once it's ready, so I can retry? Thanks a lot!

**Comment by dluvian** [comment]
> Can you give me a ping once it's ready, so I can retry? Thanks a lot!

@IzzySoft I just released a new version https://github.com/dluvian/voyage/releases/tag/v0.10.0

**Comment by IzzySoft** [comment]
Thanks @dluvian – and congrats, it's RB! So tomorrow the new release will show up at IzzyOnDroid, carrying the green RB shield.

Speaking of shields: maybe you want to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link [to your app at IzzyOnDroid](https://apt.izzysoft.de/packages/com.dluvian.voyage) e.g. from your Readme here?

Leaving the issue open for the "badge question", feel free to close then :smiley:

**Comment by dluvian** [comment]
I added IzzyOnDroid to the README under the `Installation` section. I might add badges for all the listed sources in the future but right now I prefer it like it is.

**Comment by IzzySoft** [comment]
Thanks!
